### ISSUE TITLE
Gnofix

### ISSUE THREAD

**Issue by hnisonoff** [AI-sandbox/gnomix#15]
Hi! Thank you for open sourcing this great code base. I was interested in trying out your phasing correction method, gnofix, but I noticed that it has been disabled / commented out. Do you have plans to release this or are you working on different approaches? Thank you!

**Comment by guidebortoli** [comment]
Hi, I am wondering the same...
Is Gnofix and the option "True" in the command line working?

Thank you

**Comment by weekend37** [comment]
Hi! Yes, I think I can clarify all your thoughts:

The stand alone functionality of Gnofix is currently disabled. What that means is that if you have your own set of ancestry probability estimates for certain regions and want to use Gnofix to perform phasing on those probabilities, that's currently not possible. If you're interested in trying that, let us know and we'll give that functionality higher priority. 

However, the Gnofix method is called when you use G-Nomix from the commanad line with the phasing option being "True" as @guidebortoli pointed out. So if you want to use Gnofix whilst using G-Nomix, you should have no worries.

**Comment by weekend37** [comment]
Marking this as closed. 
If you wish to use the stand alone functionality of Gnofix and you are in a rush, please create another issue to let us know.
