### ISSUE TITLE
demo.ipynb has a bad script

### ISSUE THREAD

**Issue by juanbigotes** [AI-sandbox/gnomix#25]
Hello gnomix team,

I was following the demo.ipynb file to train a model and I realize that it has a wrong script:

`train_cmd = " ".join(["python3 gnomix.py",
                      query_file, genetic_map_file, output_basename, chm, phase, reference_file, sample_map_file]) + \
            " > ./demo/training_log.txt"
print("Running in command line: \n\t", train_cmd)
os.system(train_cmd) `

The order is not the same as the one you suggest in the README.me which is:

`$ python3 gnomix.py <query_file> <output_folder> <chr_nr> <phase> <genetic_map_file> <reference_file> <sample_map_file>`

If you run the script as it is in the demo.ipynb it won't work. But if you change the order as stated in the README.me it will work.

Thanks for your attention!

**Comment by weekend37** [comment]
Thanks for letting us know!
We will address this in next release.

-Helgi

**Comment by njbowen** [comment]
please leave open until next release. thx.
