### ISSUE TITLE
Confused by implausible results on array data

### ISSUE THREAD

**Issue by buyske** [AI-sandbox/gnomix#28]
I'm very confused by the implausible results I'm getting on two African American cohorts, one genotyped on an Axiom array and one on an Omni array. For each, I phased them using the Michigan server and ran gnomix against the pretrained model with the default settings other than setting "inference: best" in config.yaml

However, I am getting means of .26 for the proportion of EUR ancestry, .25 for NAT, and .44 for AHG in one cohort, and .15, .18, and .65 respectively in the other cohort. There's not a lot of individual variability; for example, in the first cohort, the min and max for AHG are .41 and .47. 

I get very similar results regardless of whether I have gnomix correct the phasing or whether I restrict to SNPs that are in the pretrained model. I'm sure I'm doing something wrong, but I'm baffled. I could use some guidance on how to debug this.

**Comment by AlexIoannidis** [comment]
These are phased and imputed using the Michigan server?

The erratic proportions are a sign that the snps are misbehaving. In particular, the high AHG ancestry is a sign that the model is attempting to fit segments using the most distant branch of the population tree, which means the model is seeing variants that it things it has never seen before. This means that something is going wrong with the merge between the snps in your data and the ones in the model. The possibilities are that the builds don't match or that although the builds match, some of your snp variants are defined off of the opposite strand to those in the model.

**Comment by buyske** [comment]
Update: I've run the data through the "HRC or 1000G Imputation preparation and checking" pipeline using CAAPA to straighten out any strand issues, and then used the Michigan imputation server for QC and phasing again with CAAPA as a reference. Did that with and without excluding palindromic SNPs, and then ran gnomix.

Unfortunately, I'm still getting the unlikely results.

**Comment by buyske** [comment]
I ended up training my own models and got entirely plausible results.
