### ISSUE TITLE
PerformanceWarning message

### ISSUE THREAD

**Issue by guidebortoli** [AI-sandbox/gnomix#6]
Hi,

I am not sure if this is actually an issue that would compromise the analysis, but there is a message at the end of the analysis as follows:

```


--------------------------------------------------------------------------------
-----------------------------------  Gnomix  -----------------------------------
--------------------------------------------------------------------------------
When using this software, please cite: 
Helgi Hilmarsson, Arvind S Kumar, Richa Rastogi, Carlos D Bustamante, 
Daniel Mas Montserrat, Alexander G Ioannidis: 
"High Resolution Ancestry Deconvolution for Next Generation Genomic Data" 
https://www.biorxiv.org/content/10.1101/2021.09.19.460980v1
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Launching in training mode...
Reading vcf file...
Getting genetic map info...
Getting sample map info...
Building founders...
Splitting sample map...
Running Simulation...
Training...
Reading data...
Building model...
Training base models...
100%|████████████████████████████████████████| 709/709 [01:04<00:00, 10.95it/s]                                      
Training smoother...
Fitting calibrator...
Evaluating model...
Re-training base models...
100%|████████████████████████████████████████| 709/709 [01:20<00:00,  8.83it/s]                                                            
Analyzing model performance...
Estimated train accuracy: 98.42%
Estimated val accuracy: 98.32%
Model, info and analysis saved at chr15/models/model_chm_chr15
--------------------------------------------------------------------------------
Launching inference...
Loading and processing query file...
- Number of SNPs from model: 1087854
- Number of SNPs from file: 30954
- Number of intersecting SNPs: 20036
- Percentage of model SNPs covered by query file: 1.8399999999999999%
Inferring ancestry on query data...
Phasing individual 493/493
Writing phased SNPs to disc...
/Users/debortoli/Downloads/arquivos_compactados/gnomix-main/src/utils.py:316: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[data_samples[i]] = genotype_person
Saving results...


```

Specifically, it is the **PerformanceWarning**

I am getting a really weird result when running gnomix...
I have an admixed sample (Native American, African and European ancestries), with a global ancestry estimate around 70% EUR, 25% AFR and 5% NAM...
The Gnomix output .msp is assigning (I've tested only on one chromosome), AFR for all windows in all samples, which is not correct...

Not sure if this PerformanceWarning might be the culprit of this...

Thanks,

**Comment by guidebortoli** [comment]
Hi Helgi,

Please, see the zipped [file](https://www.dropbox.com/s/gvn53sninb357zb/Archive.zip?dl=0) with the gmap and the reference file (which is a phased HGDP reference file for the chr15).

Guilherme

**Comment by weekend37** [comment]
Great, thanks. I'll take a look when I find time. 
Also, feel free to include the query file if possible. Then I can actually recreate your issue.

**Comment by guidebortoli** [comment]
Thanks @weekend37 . I sent you an email with the files.

**Comment by guidebortoli** [comment]
Thanks @weekend37!
So, I have done the same analysis using Xgmix and the output was slightly better (although) it was still overestimating the AFR ancestry...
And also with rfmix2, where the results were the best so far (comparing with the global ancestry with Admixture program), and also a quick admixture mapping signal analysis for a known marker related to the phenotype I am investigating (that is known to have strong signal due to an allele difference of almost 100% between AFR and EUR)...

I am not sure if the 2% overlap could be due to the fact that my study used an array genotype data while the reference is from a WGS phased from HGDP...

Regarding the genome build they are both hg38...

Guilherme

**Comment by weekend37** [comment]
Feature request added in [11](https://github.com/AI-sandbox/gnomix/issues/11). 
Marking this as closed.
