### ISSUE TITLE
Preserve header and add ALT allele to query_file_phased.vcf

### ISSUE THREAD

**Issue by obedaram** [AI-sandbox/gnomix#7]
### Feature request:
Hi all, I have two feature requests, 
1) The first is if it would be possible to preserve the header of the input VCF file in the phasing error correction file?
2) The current column output for the query_file_phased.vcf is:
POS	ID	REF	**VAR**	QUAL	FILTER	INFO	FORMAT

with all the values under **VAR** as **NA**

would it be possible to change it to
POS	ID	REF	**ALT**	QUAL	FILTER	INFO	FORMAT

and report the alternative allele?

This would make it easier for downstream analysis with plink, bcftools, etc.

Thanks!

**Comment by arvind0422** [comment]
Hi again Obed,
 We have pushed a fix to the 2 following issues:
 - Preserve header in the output phased file
 - Reflect ALT variant in the output file.
 
Hope this helps you use gnomix in your pipeline. Thanks a lot for giving our software a try and flagging issues! Please be sure to pull the latest code (PR: https://github.com/AI-sandbox/gnomix/pull/13) and let us know if there are any issues!

Thanks,
Arvind
